### ISSUE TITLE
A Web Worker API?

### ISSUE THREAD

**Issue by mohsen1** [connec/yaml-js#14]
On top of node and browser support it would be nice if we had a web-worker API too.

**Comment by mohsen1** [comment]
Here is an example use case of the Worker API:

```js
const YAMLWorker = new Worker('yaml-js.js')

const yaml = `
key: value
num: 1
`

YAMLWorker.postMessage({method: 'compose', yaml: yaml});
YAMLWorker.onmessage =(message)=> {
  console.log(message.data)
})
```

**Comment by connec** [comment]
Thanks for the issue, but I'm going to close it since this repository is going to be archived. yaml-js has been unmaintained for some time, so it would be best to use something else.
