### ISSUE TITLE
Memory leak when runing compose in worker

### ISSUE THREAD

**Issue by mohsen1** [connec/yaml-js#17]
Here is what I've done to reproduce this bug:

**1.** Make an HTML file with following content:

``` html
<html>
  <head></head>
  <body>
    <script>
    var worker = new Worker('worker.js');

    worker.onmessage = function (message) {
      console.log(message.data);
    };

    fetch('file.yaml').then(function (resp) {
      resp.text().then(function(y) {
        worker.postMessage(y);
      });
    });
    </script>
  </body>
</html>
```

**2.** Next to `index.html` make a file an name it `worker.js`, it's exactly [`yaml.js](https://github.com/connec/yaml-js/blob/master/yaml.js) file with these lines added at the end:

```
onmessage = function (message) {
    postMessage(yaml.compose(message.data));
}
```

Which is basically adding a very simple Web Worker API to yaml-js. It also fixes the bug I reported in #16 by using `this` as `global`: `var global = this;`

**3.** Make another file and name it `file.yaml`. Content of this file can be found here: http://pastebin.com/c8AYYEGF

**4.** Run a static web server like [`http-server`](https://www.npmjs.com/package/http-server) from this folder and open the browser. What I see is Chrome's "Aw! Snap!" message. When I profiled this, memory usage goes up and up until tab crashes 

![screen shot 2015-09-18 at 11 25 30 am](https://cloud.githubusercontent.com/assets/543633/9967532/0136e8b6-5df8-11e5-8490-a8c5d78a7c8b.png)

Firefox crashes also. Safari doesn't have the Fetch API so I can't test it but I'm pretty sure that would crash also.

Note that the same file and the same method is not having this issue when run in the main thread. So if you change the content of HTML file to following code, the error won't happen:

``` html
<html>
  <head></head>
  <body>
    <script src="https://rawgit.com/connec/yaml-js/master/yaml.js"></script>
    <script>
      fetch('file.yaml').then(function (resp) {
        resp.text().then(function(y) {
          console.log(yaml.compose(y));
        });
      });
    </script>
  </body>
</html>
```

You can also download all the files in one zip file from here: https://github.com/mohsen1/mohsen1.github.io/blob/b8d76793a1e81a6c35fe83de3fea322edac910db/assets/yaml.zip

This issue was originally raised in Swagger Editor: 
https://github.com/swagger-api/swagger-editor/issues/641
https://github.com/swagger-api/swagger-editor/issues/658
https://github.com/swagger-api/swagger-editor/issues/651

**Comment by connec** [comment]
Intriguing.  I'll look into this as soon as I can.

**Comment by connec** [comment]
I'm going to close it since this repository is going to be archived. yaml-js has been unmaintained for some time, so it would be best to use something else.
