### ISSUE TITLE
Accept %YAML directive?

### ISSUE THREAD

**Issue by tea-time** [connec/yaml-js#24]
Hi,

I've just been trying out your module via http://connec.github.io/yaml-js/ (thank you for providing that!) and I have a YAML file that parses only if I remove the `%YAML 1.1` directive which is the first line.

I did check out https://github.com/connec/yaml-spec and it appears this directive is not listed, so I assume this would be a feature request. (The PyYAML documentation seems to indicate it's handled there, though - see the Tokens section: http://pyyaml.org/wiki/PyYAMLDocumentation.)

Thank you!

**Comment by connec** [comment]
Nice catch!  This looks like a bug in the scanner.  I'll add a test case and fix it up asap.

**Comment by tea-time** [comment]
Sweet, thanks!

**Comment by connec** [comment]
Sorry for the huge delay, those bugs are now fixed!

**Comment by Hirse** [comment]
@connec Could you please publish the new version?

**Comment by connec** [comment]
@Hirse done 😄
