### ISSUE TITLE
Error to Install 

### ISSUE THREAD

**Issue by kattsushi** [connec/yaml-js#27]
npm install js-yaml --save
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.11

¿= ?

**Comment by connec** [comment]
[Wrong repo.](https://github.com/nodeca/js-yaml)

**Comment by connec** [comment]
I also can't reproduce the issue.

```sh
★ npm install js-yaml
/Users/...
└─┬ js-yaml@3.5.5 
  ├─┬ argparse@1.0.7 
  │ └── sprintf-js@1.0.3 
  └── esprima@2.7.2

★ npm ls
/Users/...
└─┬ js-yaml@3.5.5
  ├─┬ argparse@1.0.7
  │ └── sprintf-js@1.0.3
  └── esprima@2.7.2
```
