### ISSUE TITLE
Can't call add_constructor on Loader object

### ISSUE THREAD

**Issue by Evgenus** [connec/yaml-js#36]
In PyYAML it is possible to add constructor to loader. 
```
>>> import yaml
>>> yaml.Loader
<class 'yaml.loader.Loader'>
>>> yaml.Loader.add_constructor
<bound method BaseConstructor.add_constructor of <class 'yaml.loader.Loader'>>
```

I know there is no multiple inheritance in JS. It looks like the only way to add new tags in standalone (non-global) context is to extend `Constructor` and use it in `make_loader`. But extending coffee-script classes in pure JS is not obvious task. I think it needs `make_constructor` function. The same also stands for `Resolver` and `Presenter`.

**Comment by connec** [comment]
I'm not sure I understand the difference between the Python module and this one, can you explain?

At any rate, you're right that the process of creating an isolated loader with custom tags is a bit awkward currently. You would need to do something like:

```js
var yaml = require('yaml-js')

// If you're using ES6 (via babel or natively)
class MyConstructor extends yaml.constructor.Constructor {}
MyConstructor.add_constructor(...)

// If you're not using ES6 (bit more work)
function MyConstructor () {}
MyConstructor.add_constructor = yaml.constructor.Constructor.add_constructor
MyConstructor.add_multi_constructor = yaml.constructor.Constructor.add_multi_constructor
MyConstructor.prototype = Object.create(yaml.constructor.Constructor.prototype)
```

**Comment by connec** [comment]
I think at a minimum `make_loader` should take an object, so you can just pass `{ Constructor: MyConstructor }`.

I'm less inclined to add a factory for creating extended `Constructor`s, as that's covered in modern environments (and by most transpilers).

**Comment by Evgenus** [comment]
```javascript 
// And to actually use it...
var MyLoader = yaml.loader.make_loader(undefined, undefined, undefined, undefined, undefined, MyConstructor)
console.log(yaml.load(stream, MyLoader))
```
that will cause `TypeError: Cannot call a class as a function` because of strictness of ES6. We need to wrap `MyConstructor` class into something like [to-factory](/timoxley/to-factory)

**Comment by Evgenus** [comment]
UPD: just tried `to-factory`. it is not working for that case. 

Some more ideas:
http://justinfagnani.com/2015/12/21/real-mixins-with-javascript-classes/
http://stackoverflow.com/questions/33754152/extending-es6-classes-programmatically

**Comment by Evgenus** [comment]
What IS working
```javascript
function MyConstructor() {
    yaml.constructor.Constructor.call(this);
}
MyConstructor.__proto__ = yaml.constructor.Constructor;
MyConstructor.prototype = Object.create(yaml.constructor.Constructor.prototype);
```
but that is very verbose and hackish.

**Comment by connec** [comment]
Interesting! Thanks for investigating this.

I'll have to look at an alternative to the class-mixin shenanigans, probably as part of the updates for [CS2](https://github.com/connec/yaml-js/tree/coffeescript2).

**Comment by connec** [comment]
Closeing since this repository is going to be archived. yaml-js has been unmaintained for some time, so it would be best to use something else.
