### ISSUE TITLE
Supported Node/ECMAScript versions

### ISSUE THREAD

**Issue by kylef** [connec/yaml-js#38]
Hi, I noticed that the patch release 0.2.1 removes support for Node version 4. I can't find any note in readme regarding the supported Node/ECMAScript versions. Would you be able to clarify the supported versions for me please @connec?

**Comment by connec** [comment]
Whoops, for some reason it didn't occur to me that the update to CoffeeScript 2 would break older runtimes. I've pushed a new `0.2.3` patch that restores the previous support and pushed `0.3.0` with an `engines` flag requiring node `>=8`.

Hopefully this resolves the immediate problem. I will add a note to the README with some versioning guidance before I close this ticket.

**Comment by kylef** [comment]
Thanks for bring back a compatible version. Looks like 0.2.3 isn't published in the NPM registry. Is that a mistake?

```
npm ERR! notarget No compatible version found: yaml-js@^0.2.3
npm ERR! notarget Valid install targets:
npm ERR! notarget 0.3.0, 0.2.2, 0.2.1, 0.2.0, 0.1.5, 0.1.4, 0.1.3, 0.1.2, 0.1.1, 0.1.0, 0.0.8, 0.0.7, 0.0.6, 0.0.5, 0.0.4, 0.0.3, 0.0.2, 0.0.1
```

**Comment by connec** [comment]
Yup it seems I missed that too. Sorted now.

**Comment by kylef** [comment]
Thank you. I think we can close this, unless you have something else in mind.
