### ISSUE TITLE
why use Date.UTC ?

### ISSUE THREAD

**Issue by youyinnn** [connec/yaml-js#43]
![image](https://user-images.githubusercontent.com/23525754/53677809-d4b59b80-3cf0-11e9-8966-8516a9b1b94e.png)

It's confusing

**Comment by connec** [comment]
The [YAML 1.1 spec for timestamps](https://yaml.org/type/timestamp.html) says that, when unspecified, the timezone will be UTC:

> If the time zone is omitted, the timestamp is assumed to be specified in UTC. The time part may be omitted altogether, resulting in a date format. In such a case, the time part is assumed to be 00:00:00Z (start of day, UTC).

This is different from the behaviour of `Date`, which will use the system timezone when unspecified.

If you want to be unambiguous you can include the timezone in the YAML:

![image](https://user-images.githubusercontent.com/160652/54026220-0917d480-4195-11e9-8b6f-9ec918c3e180.png)

**Comment by connec** [comment]
I realised my timestamp formatting was wrong above 🤦‍♂️ It should be `2019-02-02 19:51:00 +8`:

![image](https://user-images.githubusercontent.com/160652/54027185-7da04280-4198-11e9-9f22-eefd6e7cb603.png)

---

You *could* override the default handling if you'd rather have it load in the system TZ, but that will make your documents less portable:

```js
const yaml = require('yaml-js')

// Create a custom "constructor" with the desired handling of timestamps
class MyConstructor extends yaml.constructor.Constructor {}
MyConstructor.add_constructor('tag:yaml.org,2002:timestamp', node => new Date(node.value))

// Create a custom "loader" to use that constructor
const MyLoader = yaml.loader.make_loader(
  undefined, undefined, undefined, undefined, undefined,
  MyConstructor
)

// Load documents using that constructor
console.log(yaml.load('2019-02-02 19:51:00', MyLoader))
```

**Comment by youyinnn** [comment]
Thanks

And I think you should provide a setting that we could able to decide what time zone we wanted to use.

**Comment by youyinnn** [comment]
I think you could provide a setting that let us set the default time zone that we want, 

cause in many cases the YAML plain text that we use to format might not have a specific time zone, and it might be difficult that we modify the plain text in some reasons.
