### ISSUE TITLE
parse yaml error while text is a valid json string

### ISSUE THREAD

**Issue by Gpia** [connec/yaml-js#44]
I have a text, it is a valid json string but error is occured while parsing the string to json using yaml-js.

```js
var yaml = require('yaml-js');
var str = `
{
	"Tags": {
		"ManageCgroup": true,
		"domain_type": "test-development",
		"physical_storage_type": 2,
		"storage_network_type": "net2",
		"storage_type": "io8",
		"virt_type": "kvm"
	}
}
`;

var obj = JSON.parse(str)  // it is a valid json
console.log(obj);

console.log('start parse yaml');
// Loading err
//console.log(yaml.load(str)); // parse yaml error
try {
	console.log(yaml.load(str)); // parse yaml error
} catch (e) {
	console.log('parse yaml error: ', e);	
}
```

**Comment by kylef** [comment]
@Gpia That document contains tabs which are not permitted in YAML as indentation, see the following quote from YAML 1.2:

>  "To maintain portability, tab characters must not be used in indentation, since different systems treat tabs differently." [YAML 1.2 - 6.1 Indentation Space](https://yaml.org/spec/1.2/spec.html#id2777534)

Tabs must not be used, there's also some additional context in the FAQ:

> Why does YAML forbid tabs?
>
> Tabs have been outlawed since they are treated differently by different editors and tools. And since indentation is so critical to proper interpretation of YAML, this issue is just too tricky to even attempt. Indeed Guido van Rossum of Python has acknowledged that allowing TABs in Python source is a headache for many people and that were he to design Python again, he would forbid them.


https://yaml.org/faq.html

**Comment by Gpia** [comment]
@kylef thank you for your answer. but there is another question: it is said that yaml is a superset of json, but tab can be contain in json while yaml forbids tab?

**Comment by kylef** [comment]
I think https://stackoverflow.com/a/26220257 is a good detailed answer about this. Effectively, it not a complete superset as there are two (perhaps more?) cases where the behaviour can be different. Indentation tabs and the handling of duplicate keys which are not permitted in YAML.

**Comment by Gpia** [comment]
thanks.

**Comment by connec** [comment]
For more context - the YAML 1.2 spec and the YAML 1.1 spec differ on how tabs should be interpreted. The [YAML 1.1 spec section on Separation Spaces](https://yaml.org/spec/1.1/#id893014) explicitly notes:

> Outside scalar content, YAML uses space characters for separation between tokens. Note that separation must not contain tab characters.

The [YAML 1.2 spec section on Separation Spaces](https://yaml.org/spec/1.2/spec.html#id2778241), on the other hand, states:

> Outside indentation and scalar content, YAML uses white space characters for separation between tokens within a line. Note that such white space may safely include tab characters.

This library, as a port of [PyYAML](https://pyyaml.org/wiki/PyYAML), implements the YAML 1.1 spec only.

**Comment by Gpia** [comment]
@connec thanks for your answer.  So it is a difference between YAML standard 1.1 and 1.2.
