### ISSUE TITLE
compose wrong end_mark on objects in seq

### ISSUE THREAD

**Issue by AlexHolly** [connec/yaml-js#45]
Example https://codepen.io/alexholly/pen/qBBjYJq

This shows in line 50 the end line 2 but it should be 1
```
key:
  - 1
test: 2
```

This case shows it right, in line 50 the end line is 1
```
key:
  - 1
```

---
In cases with Block Style Indicator '>' or '|' end_line has also a +1 bug

Is this a solution or why is this happening?

Add this to line https://github.com/connec/yaml-js/blob/579e6f6cc513ded1740959fc57aac3dc90c5f788/lib/composer.js#L172
```
if(event.style=='>' || event.style=='|') {
  event.end_mark.line -= 1;
}
```

Test case:
```
key: >- 
 jhgjhgjhgkjhkjh
test: 1
```

**Comment by connec** [comment]
Thanks for the issue, but I'm going to close it since this repository is going to be archived. yaml-js has been unmaintained for some time, so it would be best to use something else.
